### PR TITLE
Drag and Drop feature

### PR DESCRIPTION
**Pull request by Yoyo2Code**
What's this PR do?
This PR shows the code which allows for drag and drop.

* Where should the reviewer start?

Start first in idea_card.js file to see what functionality the card has. Then work your way up to the backlog and current lists. Both hold most of the functionality.

* How should this be manually tested?

This is manually tested visually to see if the components are rendering to the page without errors in console.

* Any background context you want to provide?

This application was created over the weekend starting from nothing. It uses an external api and prioritized functionality over code organization. The application allows drag and drop, but for some reason seems to work on the second time moving the card. Also, the arrow isn't functioning property as I wanted.  The window should also be zoomed out to at least 50%. The css displayed something completely differently and isn't changing even when reverting to older commits. So it might have had to do something with the browser. ***Card registers drag functionality best when dragged to bottom-middle white spacing inside of target card***

@carmer
@neight-allen

### CODE REVIEW

**Comment by Carmer** [comment]
Hi @Yoyo2Code. I've cloned your project and was looking through the #7 dnd branch. Drag and drop appears to be working, but as you noted is not quite perfect. The problem I'm coming across is that the API fails with a 400 when I try to mark as current. 

Could you please look into this problem and report back? 

Also, I was looking through the code and noticed some used variables and other clean up tasks. Could you take care of that aswell?

**Comment by Yoyo2Code** [comment]
Hey @Carmer, there was a last minute change to put "backlog" or "current" in id instead of class. The changes weren't reflected on the 'updateStatus' ajax call, but has been updated to reflect those changes now.

**Comment by Carmer** [comment]
@Yoyo2Code Now things appear to work fine with the AJAX call, and when I refresh the page everything is in the correct position, however, the Idea Card does not update when dragged to the new position. 

Let's clean up this one last feature and finish strong.

**Comment by Yoyo2Code** [comment]
By "dragging to the new position" is there any limits as to how it's implemented? I tried making it something that will move along with it, but it's extremely difficult and wasn't successful. It updates when dragged to the bottom of the card above the target (as if trying to squeeze the card in). But is the user story implying that it has to be set on top of the card? Or would it be okay to have a space to drop it where it will allow changing positions?

**Pull request merged**
